/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteria.ui;

import paqueteria.ui.Administracion.Administracion;
import java.awt.Color;
import paqueteria.DB.ControladorDB;
import paqueteria.Usuario.Administrador;
import paqueteria.Usuario.Operador;
import paqueteria.Usuario.Recepcionista;
import paqueteria.Usuario.Usuario;
import paqueteria.ui.Operador.AreaOperador;
import paqueteria.ui.Recepcion.Recepcion;

/**
 *
 * @author sergio
 */
public class IngresoDeUsuario extends javax.swing.JFrame {

    /**
     * Creates new form IngresoDeUsuario
     */
    private static String ERROR_USUARIO_NO_EXISTENTE = "*Usuario No Existe ";
    private static String ERROR_CAMPO_NO_LLENADO = "*Campo No Llenado";
    private static String ERROR_PASSWORD_NO_CORRECTO = "*Password Incorrecto ";
    private Usuario usuarioAIngresar = null;

    public IngresoDeUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        lblPasswordOlvidado = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblErrorUsuario = new javax.swing.JLabel();
        lblErrorPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jButton1.setText("LogIn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblPasswordOlvidado.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblPasswordOlvidado.setForeground(java.awt.Color.blue);
        lblPasswordOlvidado.setText("Se me olvido mi password");
        lblPasswordOlvidado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPasswordOlvidadoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPasswordOlvidadoMouseEntered(evt);
            }
        });

        jLabel2.setText("Password:");

        jLabel3.setText("User Name:");

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setText("LOGIN");

        lblErrorUsuario.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblErrorUsuario.setForeground(java.awt.Color.red);
        lblErrorUsuario.setText("*Usuario No Existe ");
        lblErrorUsuario.setVisible(false);

        lblErrorPassword.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblErrorPassword.setForeground(java.awt.Color.red);
        lblErrorPassword.setText("*Password Incorrecto");
        lblErrorPassword.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lblPasswordOlvidado)
                        .addGap(66, 66, 66)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(88, 88, 88)
                                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(159, 159, 159)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorPassword)
                            .addComponent(lblErrorUsuario))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorUsuario))
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorPassword))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(lblPasswordOlvidado))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPasswordOlvidadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPasswordOlvidadoMouseEntered
        lblPasswordOlvidado.setForeground(new Color(97, 139, 218));
    }//GEN-LAST:event_lblPasswordOlvidadoMouseEntered

    private void lblPasswordOlvidadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPasswordOlvidadoMouseExited
        lblPasswordOlvidado.setForeground(Color.blue);
    }//GEN-LAST:event_lblPasswordOlvidadoMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        esconderMensajesError();
        if (verificarCamposLlenados()) {
            if (verificarUsuario()) {
            abrirVentaSegunJerarquia(usuarioAIngresar.getJerarquia());
        }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        esconderMensajesError();
        if (verificarCamposLlenados()) {
            if (verificarUsuario()) {
            abrirVentaSegunJerarquia(usuarioAIngresar.getJerarquia());
        }
        }
    }//GEN-LAST:event_jPasswordActionPerformed
    //Llama al metodoque devuelve el usuario si existe
    private boolean verificarUsuario() {
        boolean usuarioValido;        
        usuarioAIngresar = ControladorDB.verificarUserName(txtUserName.getText());
        if (usuarioAIngresar != null) {
            if (usuarioAIngresar.getPassword().equals(jPassword.getText())) {
                usuarioValido = true;
            } else {
                usuarioValido = false;
                lblErrorPassword.setText(ERROR_PASSWORD_NO_CORRECTO);
                lblErrorPassword.setVisible(true);
            }
        } else {
            usuarioValido = false;
            lblErrorUsuario.setText(ERROR_USUARIO_NO_EXISTENTE);
            lblErrorUsuario.setVisible(true);
        }
        return usuarioValido;
    }

    private void esconderMensajesError() {
        lblErrorPassword.setVisible(false);
        lblErrorUsuario.setVisible(false);
    }
//Abre la ventana corespondiente a la jerarquia de usuario
    private void abrirVentaSegunJerarquia(int jerarquia) {
        switch (jerarquia) {
            case 1:
                Administracion ventanaAdministracion = new Administracion((Administrador) usuarioAIngresar);
                ventanaAdministracion.setVisible(true);
                
                break;
            case 2:
                AreaOperador ventanaOperador = new AreaOperador((Operador) usuarioAIngresar);
                ventanaOperador.setVisible(true);
                break;
            case 3:
                Recepcion ventanaRecepcion = new Recepcion((Recepcionista) usuarioAIngresar);
                ventanaRecepcion.setVisible(true);
                break;
            default:
                throw new AssertionError();
        }
        this.setVisible(false);
    }
    //Verificacion que se se halla llenado los campos necesarios para continuar
    private boolean verificarCamposLlenados(){
        if (jPassword.getText().equals("")||txtUserName.getText().equals("")) {
            lblErrorUsuario.setText(ERROR_CAMPO_NO_LLENADO);
            lblErrorUsuario.setVisible(true);
            return false;
        }else{
            return true;
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel lblErrorPassword;
    private javax.swing.JLabel lblErrorUsuario;
    private javax.swing.JLabel lblPasswordOlvidado;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
