/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteria.ui.Recepcion;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import paqueteria.DB.GeneradorDeCodigos;
import paqueteria.paquetes.Cliente;
import paqueteria.paquetes.Paquete;

/**
 *
 * @author sergio
 */
public class Factura extends javax.swing.JInternalFrame {
    private Cliente cliente;
    private ArrayList<Paquete> paquetes;
    private float total;
    /**
     * Creates new form Factura
     * @param cliente
     */
    public Factura(Cliente cliente,ArrayList<Paquete> paquetes) {
        this.cliente=cliente;
        this.paquetes=paquetes;
        total=0;
        initComponents();
        agregarComponentes();
        agregarPaquetesATabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblNIT = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFactura = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Umpush", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Envios A.J.");

        jLabel2.setForeground(java.awt.Color.blue);
        jLabel2.setText("4-21 Zona 3 Quetzaltenango,GT");

        jLabel3.setForeground(java.awt.Color.blue);
        jLabel3.setText("Telefono: 555-3212-3212");

        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Factura #");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue));

        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fecha");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue));

        jLabel6.setForeground(new java.awt.Color(1, 1, 1));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NIT");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue));

        jLabel7.setForeground(new java.awt.Color(1, 1, 1));
        jLabel7.setText("Nombre:");

        jLabel8.setForeground(new java.awt.Color(1, 1, 1));
        jLabel8.setText("Direccion:");

        lblNumero.setBackground(java.awt.Color.white);
        lblNumero.setForeground(new java.awt.Color(1, 1, 1));
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("-");
        lblNumero.setOpaque(true);

        lblFecha.setBackground(java.awt.Color.white);
        lblFecha.setForeground(new java.awt.Color(1, 1, 1));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("-");
        lblFecha.setOpaque(true);

        lblNIT.setBackground(java.awt.Color.white);
        lblNIT.setForeground(new java.awt.Color(1, 1, 1));
        lblNIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNIT.setText("-");
        lblNIT.setOpaque(true);

        lblNombre.setBackground(java.awt.Color.white);
        lblNombre.setForeground(new java.awt.Color(1, 1, 1));
        lblNombre.setText("-");
        lblNombre.setOpaque(true);

        lblDireccion.setBackground(java.awt.Color.white);
        lblDireccion.setForeground(new java.awt.Color(1, 1, 1));
        lblDireccion.setText("-");
        lblDireccion.setOpaque(true);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblFactura.setForeground(new java.awt.Color(1, 1, 1));
        tblFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Descripcion", "Precio", "Monto"
            }
        ));
        tblFactura.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblFactura);
        if (tblFactura.getColumnModel().getColumnCount() > 0) {
            tblFactura.getColumnModel().getColumn(0).setMinWidth(19);
            tblFactura.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblFactura.getColumnModel().getColumn(0).setMaxWidth(21);
            tblFactura.getColumnModel().getColumn(1).setPreferredWidth(225);
            tblFactura.getColumnModel().getColumn(1).setMaxWidth(226);
            tblFactura.getColumnModel().getColumn(2).setPreferredWidth(71);
            tblFactura.getColumnModel().getColumn(2).setMaxWidth(70);
            tblFactura.getColumnModel().getColumn(3).setPreferredWidth(70);
            tblFactura.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        jScrollPane4.setViewportView(jScrollPane3);

        lblTotal.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        lblTotal.setForeground(java.awt.Color.blue);
        lblTotal.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel10.setForeground(java.awt.Color.blue);
        jLabel10.setText("TOTAL:");

        jButton1.setForeground(new java.awt.Color(1, 1, 1));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(34, 34, 34)
                                .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(79, 79, 79))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(4, 4, 4)
                            .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(22, 22, 22))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNIT)
                            .addComponent(lblFecha)))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblDireccion))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

private void agregarComponentes(){
    lblFecha.setText(String.valueOf(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))));
    if (cliente.getNit()==0) {
        lblNIT.setText("C/F");
    }else{
        lblNIT.setText(String.valueOf(cliente.getNit()));
    }
    lblNumero.setText(String.valueOf(GeneradorDeCodigos.generarCodigoPaquete()-549999));
    lblNombre.setText(cliente.getNombre());
    lblDireccion.setText(cliente.getDireccion());
}
private void agregarPaquetesATabla(){
        DefaultTableModel model = (DefaultTableModel) tblFactura.getModel();
    int aux=model.getRowCount();
    for (int i = aux; i > 0; i--) {
        model.removeRow(i-1);        
    }
            for (int i = 0; i < paquetes.size(); i++) {//Creacion de Celdas
                 model.addRow(new Object[] {"","","",""});
                 tblFactura.setValueAt(i+1, i, 0);
                 tblFactura.setValueAt(paquetes.get(i).getCodigo()+"-Paquete("+paquetes.get(i).getPeso()
                         +"lb) A "+paquetes.get(i).getRuta().getDestino().getNombre(), i, 1);
                 tblFactura.setValueAt("$"+String.format("%6.2f",paquetes.get(i).getPrecioPagado()), i, 2);
                 total=total+paquetes.get(i).getPrecioPagado();
                 tblFactura.setValueAt("$"+String.format("%6.2f",total), i, 3);                 
            }
            lblTotal.setText("$"+String.format("%6.2f",total));
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNIT;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblFactura;
    // End of variables declaration//GEN-END:variables
}
