/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteria.ui.Recepcion;

import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import paqueteria.DB.ControladorDB;
import paqueteria.paquetes.Cliente;
import paqueteria.paquetes.Paquete;

/**
 *
 * @author sergio
 */
public class IngresoPaquete extends javax.swing.JInternalFrame {

    private ArrayList<Paquete> paquetes = new ArrayList<>();
    private Cliente cliente;
    private JDesktopPane recepcion;
    protected static final String IDENTIFICADOR_CONSUMIDOR_FINAL = "C/F";
    private float total;

    /**
     * Creates new form IngresoPaquete
     *
     * @param recepcion
     */
    public IngresoPaquete(JDesktopPane recepcion) {
        this.recepcion = recepcion;
        initComponents();
        total=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaquetes = new javax.swing.JTable();
        btnCancelarPaquete = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Ingreso De Paquete");

        txtNit.setBackground(new java.awt.Color(254, 254, 254));
        txtNit.setForeground(new java.awt.Color(3, 2, 155));
        txtNit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNit.setText("C/F");
        txtNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitActionPerformed(evt);
            }
        });
        txtNit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNitKeyPressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(254, 254, 254));
        jLabel1.setForeground(new java.awt.Color(3, 2, 155));
        jLabel1.setText("Nit:");
        jLabel1.setOpaque(true);

        jButton1.setText("+ Paquete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(254, 254, 254));
        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Total:");
        jLabel2.setOpaque(true);

        lblTotal.setBackground(new java.awt.Color(254, 254, 254));
        lblTotal.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(1, 1, 1));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("$0");
        lblTotal.setOpaque(true);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 128, 0));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Destino", "Peso", "Costo", "Priorizado"
            }
        ));
        tblPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPaquetesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPaquetes);

        jScrollPane2.setViewportView(jScrollPane1);

        btnCancelarPaquete.setText("Cancelar Paquete");
        btnCancelarPaquete.setEnabled(false);
        btnCancelarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPaqueteActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregarCliente.setForeground(new java.awt.Color(3, 2, 155));
        btnAgregarCliente.setText("+");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(254, 254, 254));
        jLabel4.setForeground(new java.awt.Color(3, 2, 155));
        jLabel4.setText("Nombre:");
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(254, 254, 254));
        jLabel5.setForeground(new java.awt.Color(3, 2, 155));
        jLabel5.setText("Direccion:");
        jLabel5.setOpaque(true);

        lblNombre.setBackground(new java.awt.Color(254, 254, 254));
        lblNombre.setForeground(new java.awt.Color(3, 2, 155));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setOpaque(true);

        lblDireccion.setBackground(new java.awt.Color(254, 254, 254));
        lblDireccion.setForeground(new java.awt.Color(3, 2, 155));
        lblDireccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDireccion.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelarPaquete)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnAgregarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEnviar)
                            .addComponent(btnCancelar))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelarPaquete)
                        .addGap(46, 46, 46))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPaquetesMouseClicked
        if (tblPaquetes.getSelectedRow()>=0) {
            btnCancelarPaquete.setEnabled(true);
        }else{
            btnCancelarPaquete.setEnabled(false);
        }

    }//GEN-LAST:event_tblPaquetesMouseClicked

    private void txtNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitActionPerformed
        btnAgregarCliente.setEnabled(true);
        lblDireccion.setText("");
        lblNombre.setText("");
        if ("".equals(txtNit.getText())) {
            txtNit.setText(IDENTIFICADOR_CONSUMIDOR_FINAL);
        } else if (!txtNit.getText().equals(IDENTIFICADOR_CONSUMIDOR_FINAL)) {
            if (verficarNit()) {
                if (ControladorDB.verificarClientePorNit(Integer.parseInt(txtNit.getText())) == null) {
                    cliente=null;
                } else {
                    cliente = ControladorDB.verificarClientePorNit(Integer.parseInt(txtNit.getText()));
                    mostrarDatosCliente();
                }
            }

        }
    }//GEN-LAST:event_txtNitActionPerformed

    private void txtNitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNitKeyPressed
        btnAgregarCliente.setEnabled(false);
    }//GEN-LAST:event_txtNitKeyPressed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        NuevoCliente nuevoCliente;
        if (txtNit.getText().equals(IDENTIFICADOR_CONSUMIDOR_FINAL)) {
            nuevoCliente = new NuevoCliente(this);
        } else {
            nuevoCliente = new NuevoCliente(this, Integer.parseInt(txtNit.getText()));
        }
        recepcion.add(nuevoCliente);
        nuevoCliente.setVisible(true);
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if (verificarEnvio()) {
            int numeroEnBodega= ControladorDB.obtenerPaquetesPorEstado(1).size()+1;
            for (int i = 0; i < paquetes.size(); i++) {
                paquetes.get(i).setCliente(cliente);
                paquetes.get(i).setNumeroEnCola(numeroEnBodega+i);
                ControladorDB.guardarPaquete(paquetes.get(i));
                
            }
            this.setVisible(false);
                Factura factura = new Factura(cliente, paquetes);
                recepcion.add(factura);
                factura.setVisible(true);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NuevoPaquete nuevoPaquete = new NuevoPaquete(this,paquetes);
        recepcion.add(nuevoPaquete);
        nuevoPaquete.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPaqueteActionPerformed
        paquetes.remove(tblPaquetes.getSelectedRow());
        agregarPaquetesATabla();
        sumarTotal();
         btnCancelarPaquete.setEnabled(false);
    }//GEN-LAST:event_btnCancelarPaqueteActionPerformed
    private boolean verficarNit() {
        try {
            int aux = Integer.parseInt(txtNit.getText());
            return true;
        } catch (NumberFormatException e) {
            txtNit.setText("NIT INVALIDO");
            btnAgregarCliente.setEnabled(false);
            return false;
        }
    }

    private void mostrarDatosCliente() {
        lblNombre.setText(cliente.getNombre());
        lblDireccion.setText(cliente.getDireccion());
        btnAgregarCliente.setEnabled(false);
    }

    protected void recibirCliente(Cliente cliente) {
        this.cliente = cliente;
        mostrarDatosCliente();
    }
    protected void recibirPaquete(Paquete paquete) {
        paquetes.add(paquete);
        agregarPaquetesATabla();
        sumarTotal();
    }
    private boolean  verificarEnvio(){
        if (cliente==null) {
            JOptionPane.showMessageDialog(this,"Cliente No Registrado", "Error Al Enviar", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if (paquetes.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Faltan Los Paquetes", "Error Al Enviar", JOptionPane.ERROR_MESSAGE);
           return false; 
        }else{
            return true;
        }
    }
private void agregarPaquetesATabla(){
    DefaultTableModel model = (DefaultTableModel) tblPaquetes.getModel();
    int aux=model.getRowCount();
    for (int i = aux; i > 0; i--) {
        model.removeRow(i-1);
        
    }
            for (int i = 0; i < paquetes.size(); i++) {//Creacion de Celdas
                 model.addRow(new Object[] {"","","","",""});
                 tblPaquetes.setValueAt(paquetes.get(i).getCodigo(), i, 0);
                 tblPaquetes.setValueAt(paquetes.get(i).getRuta().getDestino().getNombre(), i, 1);
                 tblPaquetes.setValueAt(paquetes.get(i).getPeso(), i, 2);
                 tblPaquetes.setValueAt(String.format("%6.2f",paquetes.get(i).getPrecioPagado()), i, 3);
                 if (paquetes.get(i).isPriorizado()) {
                    tblPaquetes.setValueAt("Si", i, 4);
                }else{
                     tblPaquetes.setValueAt("No", i, 4);
                 }
                 
            }

           
}
private void sumarTotal(){
    for (int i = 0; i < paquetes.size(); i++) {
        total=total+paquetes.get(i).getPrecioPagado();        
    }
    lblTotal.setText("$"+String.format("%6.2f",total));
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarPaquete;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblPaquetes;
    private javax.swing.JTextField txtNit;
    // End of variables declaration//GEN-END:variables
}
