/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteria.ui.Administracion;

import paqueteria.Usuario.Administrador;
import paqueteria.ui.IngresoDeUsuario;

/**
 *
 * @author sergio
 */
public class Administracion extends javax.swing.JFrame {
    private Administrador user=null;
    /**
     * Creates new form Administracion
     * @param user
     */
    public Administracion(Administrador user) {
        this.user=user;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        dskVentana = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuRutas = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuEditarRuta = new javax.swing.JMenuItem();
        menuDesactivar = new javax.swing.JMenuItem();
        menuPuntos = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        menuItemTarifa = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        menuTarifas = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        menuUsuario = new javax.swing.JMenu();
        mItemLogOut = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu3.setText("jMenu3");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administracion");
        setResizable(false);

        dskVentana.setBackground(new java.awt.Color(140, 130, 238));

        jMenuBar1.setBackground(new java.awt.Color(254, 254, 254));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 5, 142)));

        menuUsuarios.setBackground(new java.awt.Color(254, 254, 254));
        menuUsuarios.setForeground(new java.awt.Color(1, 1, 1));
        menuUsuarios.setText("Usuarios");
        menuUsuarios.setBorderPainted(true);
        menuUsuarios.setOpaque(true);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setBackground(new java.awt.Color(254, 254, 254));
        jMenuItem1.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem1.setText("Nuevo");
        jMenuItem1.setOpaque(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuUsuarios.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setBackground(new java.awt.Color(254, 254, 254));
        jMenuItem2.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem2.setText("Existentes");
        jMenuItem2.setOpaque(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuUsuarios.add(jMenuItem2);

        jMenuBar1.add(menuUsuarios);

        menuRutas.setBackground(new java.awt.Color(254, 254, 254));
        menuRutas.setForeground(new java.awt.Color(1, 1, 1));
        menuRutas.setText("Rutas");
        menuRutas.setOpaque(true);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setBackground(new java.awt.Color(254, 254, 254));
        jMenuItem3.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem3.setText("Nuevo");
        jMenuItem3.setOpaque(true);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuRutas.add(jMenuItem3);

        menuEditarRuta.setBackground(new java.awt.Color(254, 254, 254));
        menuEditarRuta.setForeground(new java.awt.Color(1, 1, 1));
        menuEditarRuta.setText("Editar");
        menuEditarRuta.setOpaque(true);
        menuEditarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarRutaActionPerformed(evt);
            }
        });
        menuRutas.add(menuEditarRuta);

        menuDesactivar.setBackground(new java.awt.Color(254, 254, 254));
        menuDesactivar.setForeground(new java.awt.Color(1, 1, 1));
        menuDesactivar.setText("Desactivar");
        menuDesactivar.setOpaque(true);
        menuDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDesactivarActionPerformed(evt);
            }
        });
        menuRutas.add(menuDesactivar);

        jMenuBar1.add(menuRutas);

        menuPuntos.setBackground(new java.awt.Color(254, 254, 254));
        menuPuntos.setForeground(new java.awt.Color(1, 1, 1));
        menuPuntos.setText("Puntos De Control");
        menuPuntos.setOpaque(true);

        jMenuItem8.setBackground(new java.awt.Color(254, 254, 254));
        jMenuItem8.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem8.setText("Editar");
        jMenuItem8.setOpaque(true);
        menuPuntos.add(jMenuItem8);

        menuItemTarifa.setBackground(new java.awt.Color(254, 254, 254));
        menuItemTarifa.setForeground(new java.awt.Color(1, 1, 1));
        menuItemTarifa.setText("Tarifa De Operacion");
        menuItemTarifa.setOpaque(true);
        menuItemTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTarifaActionPerformed(evt);
            }
        });
        menuPuntos.add(menuItemTarifa);

        jMenuBar1.add(menuPuntos);

        jMenu5.setBackground(new java.awt.Color(254, 254, 254));
        jMenu5.setForeground(new java.awt.Color(1, 1, 1));
        jMenu5.setText("Destinos");
        jMenu5.setOpaque(true);

        jMenuItem10.setText("Nuevo Destino");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuBar1.add(jMenu5);

        menuTarifas.setBackground(new java.awt.Color(254, 254, 254));
        menuTarifas.setForeground(new java.awt.Color(1, 1, 1));
        menuTarifas.setText("Tarifas");
        menuTarifas.setOpaque(true);
        menuTarifas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTarifasMouseClicked(evt);
            }
        });
        menuTarifas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTarifasActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuTarifas);

        jMenu2.setBackground(new java.awt.Color(254, 254, 254));
        jMenu2.setForeground(new java.awt.Color(1, 1, 1));
        jMenu2.setText("Ayuda");
        jMenu2.setOpaque(true);
        jMenuBar1.add(jMenu2);

        jMenu4.setText("                                                                              ");
        jMenu4.setEnabled(false);
        jMenuBar1.add(jMenu4);

        menuUsuario.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        menuUsuario.setForeground(new java.awt.Color(1, 1, 1));
        menuUsuario.setText("user");

        mItemLogOut.setText("Log Out");
        mItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemLogOutActionPerformed(evt);
            }
        });
        menuUsuario.add(mItemLogOut);

        menuUsuario.setText(user.getUserName());

        jMenuBar1.add(menuUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dskVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        NuevoUsuario nuevo = new NuevoUsuario();
        dskVentana.add(nuevo);
        nuevo.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemLogOutActionPerformed
       IngresoDeUsuario logOut = new IngresoDeUsuario();
       logOut.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_mItemLogOutActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        NuevaRuta ruta = new NuevaRuta(dskVentana);
        dskVentana.add(ruta);
        ruta.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        NuevoDestino nuevoDestino = new NuevoDestino();
        dskVentana.add(nuevoDestino);
        nuevoDestino.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void menuTarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTarifasActionPerformed
        CambioTarifas cambioTarifas = new CambioTarifas();
        dskVentana.add(cambioTarifas);
        cambioTarifas.setVisible(true);
    }//GEN-LAST:event_menuTarifasActionPerformed

    private void menuItemTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTarifaActionPerformed
        CambioTarifas cambioTarifas = new CambioTarifas();
        dskVentana.add(cambioTarifas);
        cambioTarifas.setVisible(true);
    }//GEN-LAST:event_menuItemTarifaActionPerformed

    private void menuTarifasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTarifasMouseClicked
        CambioTarifas cambioTarifas = new CambioTarifas();
        dskVentana.add(cambioTarifas);
        cambioTarifas.setVisible(true);
        
    }//GEN-LAST:event_menuTarifasMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        UsuariosExistentes usuariosExistentes = new UsuariosExistentes(user,this);
        dskVentana.add(usuariosExistentes);
        usuariosExistentes.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuEditarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarRutaActionPerformed
       MostradorDeRutas nuevaMostador= new MostradorDeRutas(MostradorDeRutas.IDENTIFICADO_EDITADOR);
       dskVentana.add(nuevaMostador);
       nuevaMostador.setVisible(true);
    }//GEN-LAST:event_menuEditarRutaActionPerformed

    private void menuDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDesactivarActionPerformed
      MostradorDeRutas nuevaMostador= new MostradorDeRutas(MostradorDeRutas.IDENTIFICADO_DESACTIVADOR);
       dskVentana.add(nuevaMostador);
       nuevaMostador.setVisible(true);  
    }//GEN-LAST:event_menuDesactivarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskVentana;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem mItemLogOut;
    private javax.swing.JMenuItem menuDesactivar;
    private javax.swing.JMenuItem menuEditarRuta;
    private javax.swing.JMenuItem menuItemTarifa;
    private javax.swing.JMenu menuPuntos;
    private javax.swing.JMenu menuRutas;
    private javax.swing.JMenu menuTarifas;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
