/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteria.ui.Administracion;

import paqueteria.Usuario.Administrador;
import paqueteria.ui.IngresoDeUsuario;

/**
 *
 * @author sergio
 */
public class Administracion extends javax.swing.JFrame {
    private Administrador user=null;
    /**
     * Creates new form Administracion
     * @param user
     */
    public Administracion(Administrador user) {
        this.user=user;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        dskpanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuRutas = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuPuntos = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        menuUsuario = new javax.swing.JMenu();
        mItemLogOut = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu3.setText("jMenu3");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        dskpanel.setBackground(new java.awt.Color(140, 130, 238));

        jMenuBar1.setBackground(new java.awt.Color(254, 254, 254));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 5, 142)));

        menuUsuarios.setBackground(new java.awt.Color(254, 254, 254));
        menuUsuarios.setForeground(new java.awt.Color(1, 1, 1));
        menuUsuarios.setText("Usuarios");
        menuUsuarios.setBorderPainted(true);
        menuUsuarios.setOpaque(true);

        jMenuItem1.setBackground(new java.awt.Color(254, 254, 254));
        jMenuItem1.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem1.setText("Nuevo");
        jMenuItem1.setOpaque(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuUsuarios.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(254, 254, 254));
        jMenuItem2.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem2.setText("Eliminar");
        jMenuItem2.setOpaque(true);
        menuUsuarios.add(jMenuItem2);

        jMenuBar1.add(menuUsuarios);

        menuRutas.setBackground(new java.awt.Color(254, 254, 254));
        menuRutas.setForeground(new java.awt.Color(1, 1, 1));
        menuRutas.setText("Rutas");
        menuRutas.setOpaque(true);

        jMenuItem3.setBackground(new java.awt.Color(254, 254, 254));
        jMenuItem3.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem3.setText("Nuevo");
        jMenuItem3.setOpaque(true);
        menuRutas.add(jMenuItem3);

        jMenuItem6.setBackground(new java.awt.Color(254, 254, 254));
        jMenuItem6.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem6.setText("Editar");
        jMenuItem6.setOpaque(true);
        menuRutas.add(jMenuItem6);

        jMenuItem5.setBackground(new java.awt.Color(254, 254, 254));
        jMenuItem5.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem5.setText("Desactivar");
        jMenuItem5.setOpaque(true);
        menuRutas.add(jMenuItem5);

        jMenuBar1.add(menuRutas);

        menuPuntos.setBackground(new java.awt.Color(254, 254, 254));
        menuPuntos.setForeground(new java.awt.Color(1, 1, 1));
        menuPuntos.setText("Puntos De Control");
        menuPuntos.setOpaque(true);

        jMenuItem7.setBackground(new java.awt.Color(254, 254, 254));
        jMenuItem7.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem7.setText("Nuevo");
        jMenuItem7.setOpaque(true);
        menuPuntos.add(jMenuItem7);

        jMenuItem8.setBackground(new java.awt.Color(254, 254, 254));
        jMenuItem8.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem8.setText("Editar");
        jMenuItem8.setOpaque(true);
        menuPuntos.add(jMenuItem8);

        jMenuItem4.setBackground(new java.awt.Color(254, 254, 254));
        jMenuItem4.setForeground(new java.awt.Color(1, 1, 1));
        jMenuItem4.setText("Tarifa De Operacion");
        jMenuItem4.setOpaque(true);
        menuPuntos.add(jMenuItem4);

        jMenuBar1.add(menuPuntos);

        jMenu2.setBackground(new java.awt.Color(254, 254, 254));
        jMenu2.setForeground(new java.awt.Color(1, 1, 1));
        jMenu2.setText("Ayuda");
        jMenu2.setOpaque(true);
        jMenuBar1.add(jMenu2);

        jMenu4.setText("                                                                                                                        ");
        jMenu4.setEnabled(false);
        jMenuBar1.add(jMenu4);

        menuUsuario.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        menuUsuario.setForeground(new java.awt.Color(1, 1, 1));
        menuUsuario.setText("user");

        mItemLogOut.setText("Log Out");
        mItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemLogOutActionPerformed(evt);
            }
        });
        menuUsuario.add(mItemLogOut);

        menuUsuario.setText(user.getUserName());

        jMenuBar1.add(menuUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dskpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        NuevoUsuario nuevo = new NuevoUsuario();
        dskpanel.add(nuevo);
        nuevo.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemLogOutActionPerformed
       IngresoDeUsuario logOut = new IngresoDeUsuario();
       logOut.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_mItemLogOutActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskpanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem mItemLogOut;
    private javax.swing.JMenu menuPuntos;
    private javax.swing.JMenu menuRutas;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
