/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteria.ui.Administracion;

import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import paqueteria.DB.TransferenciasDB;
import paqueteria.Ruta.PuntoDeControl;

/**
 *
 * @author sergio
 */
public class EditacionDePuntos extends javax.swing.JInternalFrame {

    private ArrayList<PuntoDeControl> puntos;
    private JDesktopPane panel;

    /**
     * Creates new form EditacionDePuntos
     * @param panel
     */
    public EditacionDePuntos(JDesktopPane panel) {
        initComponents();
        this.panel= panel;
        puntos = TransferenciasDB.obtenerTodosLosPuntos();
        agregarPuntosATabal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPuntos = new javax.swing.JTable();
        txtBuscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Editacion De Puntos De Control");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admi.png"))); // NOI18N

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tblPuntos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Ruta", "Capacidad", "Operador", "Tarifa", "Paquetes"
            }
        ));
        tblPuntos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPuntosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPuntos);
        if (tblPuntos.getColumnModel().getColumnCount() > 0) {
            tblPuntos.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblPuntos.getColumnModel().getColumn(0).setMaxWidth(100);
            tblPuntos.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblPuntos.getColumnModel().getColumn(1).setMaxWidth(100);
            tblPuntos.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblPuntos.getColumnModel().getColumn(2).setMaxWidth(80);
            tblPuntos.getColumnModel().getColumn(5).setPreferredWidth(80);
            tblPuntos.getColumnModel().getColumn(5).setMaxWidth(80);
        }

        jScrollPane2.setViewportView(jScrollPane1);

        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel1.setText("Buscar Por Codigo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(287, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPuntosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPuntosMouseClicked
        if (tblPuntos.getSelectedRow() >= 0) {
            btnEditar.setEnabled(true);
        } else {
            btnEditar.setEnabled(false);
        }
    }//GEN-LAST:event_tblPuntosMouseClicked

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        buscar(txtBuscador.getText());
        agregarPuntosATabal();
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
        buscar(txtBuscador.getText());
        agregarPuntosATabal();
    }//GEN-LAST:event_txtBuscadorKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (TransferenciasDB.obtenerPaquetesPorPunto(puntos.get(tblPuntos.getSelectedRow()).getCodigo()).size()>0) {
          JOptionPane.showMessageDialog(this,"Este Punto Cuenta con Paquetes En Cola","Error Al Querer Editar", JOptionPane.ERROR_MESSAGE);   
        }else{
        NuevoPunto editarPunto = new NuevoPunto(puntos.get(tblPuntos.getSelectedRow()));
        this.setVisible(false);
        panel.add(editarPunto);
        editarPunto.setVisible(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed
    private void buscar(String palabra) {
        if (!"".equals(palabra)) {
            ArrayList<PuntoDeControl> aux = new ArrayList<>();
            for (int i = 0; i < puntos.size(); i++) {
                if (String.valueOf(puntos.get(i).getCodigo()).startsWith(palabra)) {
                    aux.add(puntos.get(i));
                }
            }
            boolean auxiliar;
            for (int i = 0; i < puntos.size(); i++) {
                auxiliar = true;
                for (int j = 0; j < aux.size(); j++) {
                    if (puntos.get(i).getCodigo() == aux.get(j).getCodigo()) {
                        auxiliar = false;
                    }
                }
                if (auxiliar) {
                    aux.add(puntos.get(i));
                }
            }
            puntos = aux;
        }

    }

    private void agregarPuntosATabal() {
        DefaultTableModel model = (DefaultTableModel) tblPuntos.getModel();
        int aux = model.getRowCount();
        for (int i = aux; i > 0; i--) {
            model.removeRow(i - 1);

        }
        for (int i = 0; i < puntos.size(); i++) {//Creacion de Celdas
            model.addRow(new Object[]{"", "", "", "", ""});
            tblPuntos.setValueAt(puntos.get(i).getCodigo(), i, 0);
            tblPuntos.setValueAt(puntos.get(i).getCodigoRuta(), i, 1);
            tblPuntos.setValueAt(puntos.get(i).getCapacidad(), i, 2);
            tblPuntos.setValueAt(puntos.get(i).getUser().getUserName(), i, 3);
            tblPuntos.setValueAt("$" + String.format("%6.2f", puntos.get(i).getPrecio().get(puntos.get(i).getPrecio().size() - 1).getPrecio()), i, 4);
            tblPuntos.setValueAt(TransferenciasDB.obtenerPaquetesPorPunto(puntos.get(i).getCodigo()).size(), i, 5);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPuntos;
    private javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables
}
