/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteria.ui.Administracion;

import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import paqueteria.DB.ControladorDB;
import paqueteria.Ruta.Destino;
import paqueteria.Ruta.Tarifa;

/**
 *
 * @author sergio
 */
public class EditarDestino extends javax.swing.JInternalFrame {

    private Destino destinoAEditar;
    private ArrayList<Destino> destinosPosibles;

    /**
     * Creates new form EditarDestino
     */
    public EditarDestino() {
        initComponents();
        mostrarDestinos();
    }

    private void mostrarDestinos() {
        destinosPosibles = ControladorDB.obtenerDestino();
        cBoxDestinos.removeAllItems();
        if (destinosPosibles != null) {
            for (int i = 0; i < destinosPosibles.size(); i++) {
                cBoxDestinos.addItem(String.valueOf(destinosPosibles.get(i).getCodigo()) + " - " + destinosPosibles.get(i).getNombre());
            }
        } else {
            cBoxDestinos.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cBoxDestinos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        spinnerCouta = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Editar Destino");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admi.png"))); // NOI18N

        cBoxDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxDestinosActionPerformed(evt);
            }
        });

        jLabel4.setText("Codigo - Nombre");

        spinnerCouta.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.01f));
        spinnerCouta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerCoutaStateChanged(evt);
            }
        });

        jLabel1.setText("Couta De Destino($):");

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spinnerCouta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(cBoxDestinos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cBoxDestinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerCouta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cBoxDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxDestinosActionPerformed
        if (destinosPosibles != null) {
            if (cBoxDestinos.getItemCount()>0) {
                            destinoAEditar = destinosPosibles.get(cBoxDestinos.getSelectedIndex());
            spinnerCouta.setValue(destinoAEditar.getPrecio().get(destinoAEditar.getPrecio().size() - 1).getPrecio());
            }

        }
    }//GEN-LAST:event_cBoxDestinosActionPerformed

    private void spinnerCoutaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerCoutaStateChanged
        if ((float) spinnerCouta.getValue() != destinoAEditar.getPrecio().get(destinoAEditar.getPrecio().size() - 1).getPrecio()) {
            btnEditar.setEnabled(true);
        } else {
            btnEditar.setEnabled(false);
        }
    }//GEN-LAST:event_spinnerCoutaStateChanged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        ControladorDB.guardarPrecioDestino(destinoAEditar,new Tarifa((float) spinnerCouta.getValue(), LocalDateTime.now()));
        mostrarDestinos();
        JOptionPane.showMessageDialog(this,"Destino Codigo: "+ destinoAEditar.getCodigo() + " Actualizado ", "Destino Actualizado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cBoxDestinos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spinnerCouta;
    // End of variables declaration//GEN-END:variables
}
