/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteria.ui.Administracion;

import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import paqueteria.DB.ControladorDB;
import paqueteria.DB.TransferenciasDB;
import paqueteria.GeneradorHTML;
import paqueteria.Ruta.Ruta;

/**
 *
 * @author sergio
 */
public class GananciaDeRutas extends javax.swing.JInternalFrame {

    private ArrayList<Ruta> rutas;
    private boolean filtrarFechas;

    /**
     * Creates new form GananciaDeRutas
     */
    public GananciaDeRutas() {
        filtrarFechas = false;
        initComponents();
        rutas = ControladorDB.obtenerRutas();
        mostrarRutasEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barRenderer1 = new org.jfree.chart.renderer.category.BarRenderer();
        btnExportar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblErrorRutas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRuta = new javax.swing.JTable();
        dateInicio = new com.toedter.calendar.JDateChooser();
        dateFinal = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        lblErrorFechas = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Ganancias De Rutas");

        btnExportar.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnExportar.setText("Exportar(HTML)");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");

        lblErrorRutas.setText("No Existen Rutas");
        lblErrorRutas.setVisible(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel1.setText("Buscar Por Codigo:");

        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });

        jLabel2.setText("Fecha Inicio:");

        jLabel3.setText("Fecha Final:");

        jButton2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButton2.setText("Filtrar(Fecha)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblRuta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Destino", "Estado", "Ingresos", "Perdidas", "Ganancias"
            }
        ));
        jScrollPane1.setViewportView(tblRuta);

        jScrollPane2.setViewportView(jScrollPane1);

        jButton3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButton3.setText("Reset Filtracion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblErrorFechas.setText("Fechas Incorectas");
        lblErrorFechas.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(lblErrorRutas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel2)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(lblErrorFechas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(lblErrorFechas))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jButton2))
                    .addComponent(dateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportar)
                    .addComponent(btnSalir)
                    .addComponent(lblErrorRutas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        buscar(txtBuscador.getText());
        mostrarRutasEnTabla();
        txtBuscador.setText("");
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void txtBuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscadorKeyTyped

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
        buscar(txtBuscador.getText());
        mostrarRutasEnTabla();
    }//GEN-LAST:event_txtBuscadorKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lblErrorFechas.setVisible(false);
        if(dateFinal.getDate()==null && dateInicio.getDate()==null){
            lblErrorFechas.setVisible(true);
        }else if(dateFinal.getDate()==null && dateInicio.getDate().after(Date.from(Instant.now()))){
        lblErrorFechas.setVisible(true);
    }else if((dateFinal.getDate()!=null&&dateInicio.getDate()!=null)  &&dateInicio.getDate().after(dateFinal.getDate())){
        lblErrorFechas.setVisible(true);
    }else{
        filtrarFechas = true;
        mostrarRutasEnTabla();
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        lblErrorFechas.setVisible(false);
        filtrarFechas=false;
        dateInicio.setDate(null);
        dateFinal.setDate(null);
        mostrarRutasEnTabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        GeneradorHTML.generarReprote(tblRuta, title, LocalDate.now());
                JOptionPane.showMessageDialog(this, "Archivo HTML se encuentra en la carpeta 'Reportes'", "Exportado Correctamente", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnExportarActionPerformed
    //Filtra las rutas conforme a la palabra que es el codigo
    private void buscar(String palabra) {
        if (!"".equals(palabra)) {
            ArrayList<Ruta> aux = new ArrayList<>();
            for (int i = 0; i < rutas.size(); i++) {
                if (String.valueOf(rutas.get(i).getCodigo()).startsWith(palabra)) {
                    aux.add(rutas.get(i));
                }
            }
            boolean auxiliar;
            for (int i = 0; i < rutas.size(); i++) {
                auxiliar = true;
                for (int j = 0; j < aux.size(); j++) {
                    if (rutas.get(i).getCodigo() == aux.get(j).getCodigo()) {
                        auxiliar = false;
                    }
                }
                if (auxiliar) {
                    aux.add(rutas.get(i));
                }
            }
            rutas = aux;
        }

    }
//Muestra los datos de las rutas en las tablas
        private void mostrarRutasEnTabla() {
            if (rutas.size() > 0) {
                DefaultTableModel model = (DefaultTableModel) tblRuta.getModel();
                int aux = model.getRowCount();
                for (int i = aux; i > 0; i--) {
                    model.removeRow(i - 1);
                }
                for (int i = 0; i < rutas.size(); i++) {//Creacion de Celdas
                    model.addRow(new Object[]{"", "", "", "", "", ""});
                    tblRuta.setValueAt(rutas.get(i).getCodigo(), i, 0);
                    if (rutas.get(i).isEstado()) {
                        tblRuta.setValueAt("Activado", i, 2);
                    } else {
                        tblRuta.setValueAt("Desactivado", i, 2);
                    }

                    tblRuta.setValueAt(rutas.get(i).getDestino().getNombre(), i, 1);
                    float ganacias=0;
                    float perdida=0;
                    //En caso de querer filtrar por fechas
                    if (filtrarFechas) {
                        LocalDateTime inicioDate;
                        LocalDateTime finalDate;
                        if (dateInicio.getDate()==null) {
                            inicioDate= LocalDateTime.of(2000,1,1, 0,0);
                        }else{
                            inicioDate=LocalDateTime.of(dateInicio.getDate().getYear()+1900,dateInicio.getDate().getMonth()+1,dateInicio.getDate().getDate(),0,0);
                        }
                        if (dateFinal.getDate()==null) {
                            finalDate= LocalDateTime.now();
                        }else{
                            finalDate=LocalDateTime.of(dateFinal.getDate().getYear()+1900,dateFinal.getDate().getMonth()+1,dateFinal.getDate().getDate(),0,0);
                        }
                        ganacias= TransferenciasDB.obtenerGananciasPorRutaFecha(rutas.get(i).getCodigo(),inicioDate,finalDate);
                        perdida= TransferenciasDB.obtenerPerdidaPorRutaFecha(rutas.get(i).getCodigo(),inicioDate,finalDate);
                    } else {
                        ganacias = TransferenciasDB.obtenerGananciasPorRuta(rutas.get(i).getCodigo());                    
                        perdida = TransferenciasDB.obtenerPerdidaPorRuta(rutas.get(i).getCodigo());

                    }
                    tblRuta.setValueAt("$" + String.format("%6.2f", ganacias), i, 3);
                    tblRuta.setValueAt("$" + String.format("%6.2f", perdida), i, 4);
                        tblRuta.setValueAt("$" + String.format("%6.2f", ganacias - perdida), i, 5);
                }
            } else {
                lblErrorRutas.setVisible(true);
            }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jfree.chart.renderer.category.BarRenderer barRenderer1;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnSalir;
    private com.toedter.calendar.JDateChooser dateFinal;
    private com.toedter.calendar.JDateChooser dateInicio;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblErrorFechas;
    private javax.swing.JLabel lblErrorRutas;
    private javax.swing.JTable tblRuta;
    private javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables
}
