/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteria.ui.Administracion;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import paqueteria.DB.ControladorDB;
import paqueteria.DB.TransferenciasDB;
import paqueteria.GeneradorHTML;
import paqueteria.paquetes.Cliente;
import paqueteria.paquetes.Paquete;

/**
 *
 * @author sergio
 */
public class GananciaClientes extends javax.swing.JInternalFrame {
private ArrayList<Cliente> clientes;
    /**
     * Creates new form GananciaClientes
     */
    public GananciaClientes() {
        initComponents();
        obtenerCLientes();
        mostrarRutasEnTabla();
    }
private void obtenerCLientes(){
    clientes= new ArrayList<>();
ArrayList codigos = ControladorDB.obtenerCodigoDeClientes();
    for (int i = 0; i < codigos.size(); i++) {
        clientes.add(ControladorDB.verificarClientePorCodigo((Integer)codigos.get(i)));        
    }
}
    private void mostrarRutasEnTabla() {
        if (clientes.size() > 0) {
            DefaultTableModel model = (DefaultTableModel) tblClientes.getModel();
            int aux = model.getRowCount();
            for (int i = aux; i > 0; i--) {
                model.removeRow(i - 1);
            }
            for (int i = 0; i < clientes.size(); i++) {//Creacion de Celdas
                model.addRow(new Object[]{"", "", "", "", "", ""});
                tblClientes.setValueAt(clientes.get(i).getCodigo(), i, 0);
                if (clientes.get(i).getNit()==0) {
                    tblClientes.setValueAt("C/F", i, 1);
                } else {
                    tblClientes.setValueAt(clientes.get(i).getNit(), i, 1);
                }

                tblClientes.setValueAt(clientes.get(i).getNombre(), i, 2);
                ArrayList<Paquete> paquetes = TransferenciasDB.obtenerPaquetesPorCliente(clientes.get(i).getCodigo());
                tblClientes.setValueAt(paquetes.size(), i, 3);
                float ganacias=0;
                float perdidas=0;
                for (int j = 0; j < paquetes.size(); j++) {
                    ganacias=ganacias+paquetes.get(j).getPrecioPagado();
                    perdidas=perdidas+paquetes.get(j).getPrecioPerdido();
                }
                tblClientes.setValueAt("$"+String.format("%6.2f",ganacias), i, 4);
                tblClientes.setValueAt("$"+String.format("%6.2f",perdidas), i, 5);
                tblClientes.setValueAt("$"+String.format("%6.2f",ganacias-perdidas), i, 6);
            }
        } else {
            lblError.setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblError = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        txtBuscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("CLientes");
        setToolTipText("");

        lblError.setText("No Existen Clientes");
        lblError.setVisible(false);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnExportar.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnExportar.setText("Exporta(Html)");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "NIT", "Nombre", "Paquetes", "Ingresos", "Costos", "Ganancias"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        jScrollPane2.setViewportView(jScrollPane1);

        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel1.setText("Buscar Por Codigo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(lblError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblError)
                        .addComponent(btnExportar))
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        buscar(txtBuscador.getText());
        mostrarRutasEnTabla();
        txtBuscador.setText("");
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void txtBuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscadorKeyTyped

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
        buscar(txtBuscador.getText());
        mostrarRutasEnTabla();
    }//GEN-LAST:event_txtBuscadorKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        GeneradorHTML.generarReprote(tblClientes, title, LocalDate.now());
        JOptionPane.showMessageDialog(this, "Archivo HTML se encuentra en la carpeta 'Reportes'", "Exportado Correctamente", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnExportarActionPerformed
    private void buscar(String palabra) {
        if (!"".equals(palabra)) {
            ArrayList<Cliente> aux = new ArrayList<>();
            for (int i = 0; i < clientes.size(); i++) {
                if (String.valueOf(clientes.get(i).getCodigo()).startsWith(palabra)) {
                    aux.add(clientes.get(i));
                }
            }
            boolean auxiliar;
            for (int i = 0; i < clientes.size(); i++) {
                auxiliar = true;
                for (int j = 0; j < aux.size(); j++) {
                    if (clientes.get(i).getCodigo() == aux.get(j).getCodigo()) {
                        auxiliar = false;
                    }
                }
                if (auxiliar) {
                    aux.add(clientes.get(i));
                }
            }
            clientes = aux;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblError;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables
}
