/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteria.ui.Administracion;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import paqueteria.DB.ControladorDB;
import paqueteria.DB.TransferenciasDB;
import paqueteria.Ruta.Ruta;

/**
 *
 * @author sergio
 */
public class PaquetesEnRuta extends javax.swing.JInternalFrame {

    private ArrayList<Ruta> rutas;
    private boolean ascendente;

    /**
     * Creates new form PaquetesEnRuta
     */
    public PaquetesEnRuta() {
        ascendente = false;

        initComponents();
        rutas = ControladorDB.obtenerRutas();
        mostrarRutasEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRuta = new javax.swing.JTable();
        btnFiltrar = new javax.swing.JButton();
        txtBuscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblErrorRutas = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Paquetes En Ruta");

        tblRuta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Destino", "Estado", "Paq. En Ruta", "Paq. Salido", "Total Paq."
            }
        ));
        jScrollPane1.setViewportView(tblRuta);
        if (tblRuta.getColumnModel().getColumnCount() > 0) {
            tblRuta.getColumnModel().getColumn(0).setPreferredWidth(75);
            tblRuta.getColumnModel().getColumn(0).setMaxWidth(75);
            tblRuta.getColumnModel().getColumn(1).setPreferredWidth(110);
            tblRuta.getColumnModel().getColumn(1).setMaxWidth(110);
            tblRuta.getColumnModel().getColumn(2).setPreferredWidth(85);
            tblRuta.getColumnModel().getColumn(2).setMaxWidth(85);
            tblRuta.getColumnModel().getColumn(3).setPreferredWidth(95);
            tblRuta.getColumnModel().getColumn(3).setMaxWidth(95);
            tblRuta.getColumnModel().getColumn(4).setPreferredWidth(85);
            tblRuta.getColumnModel().getColumn(4).setMaxWidth(85);
            tblRuta.getColumnModel().getColumn(5).setPreferredWidth(85);
            tblRuta.getColumnModel().getColumn(5).setMaxWidth(85);
        }

        btnFiltrar.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        btnFiltrar.setText("Filtrar(Estado)");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel1.setText("Buscar Por Codigo:");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblErrorRutas.setText("No Existen Rutas");
        lblErrorRutas.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFiltrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lblErrorRutas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiltrar)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(lblErrorRutas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtBuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscadorKeyTyped

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        buscar(txtBuscador.getText());
        mostrarRutasEnTabla();
        txtBuscador.setText("");
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
        buscar(txtBuscador.getText());
        mostrarRutasEnTabla();
    }//GEN-LAST:event_txtBuscadorKeyReleased

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        filtrarPorEstado();
        mostrarRutasEnTabla();
    }//GEN-LAST:event_btnFiltrarActionPerformed
    private void filtrarPorEstado() {
        txtBuscador.setText("");
        ArrayList<Ruta> aux = new ArrayList<>();
        for (int i = 0; i < rutas.size(); i++) {
            if (ascendente) {
                if (rutas.get(i).isEstado()) {
                    aux.add(rutas.get(i));
                }
            } else {
                if (!rutas.get(i).isEstado()) {
                    aux.add(rutas.get(i));
                }
            }
        }
        boolean auxiliar;
        for (int i = 0; i < rutas.size(); i++) {
            auxiliar = true;
            for (int j = 0; j < aux.size(); j++) {
                if (rutas.get(i).getCodigo() == aux.get(j).getCodigo()) {
                    auxiliar = false;
                }
            }
            if (auxiliar) {
                aux.add(rutas.get(i));
            }
        }
        rutas = aux;
        ascendente = !ascendente;
    }

    private void buscar(String palabra) {
        if (!"".equals(palabra)) {
            ArrayList<Ruta> aux = new ArrayList<>();
            for (int i = 0; i < rutas.size(); i++) {
                if (String.valueOf(rutas.get(i).getCodigo()).startsWith(palabra)) {
                    aux.add(rutas.get(i));
                }
            }
            boolean auxiliar;
            for (int i = 0; i < rutas.size(); i++) {
                auxiliar = true;
                for (int j = 0; j < aux.size(); j++) {
                    if (rutas.get(i).getCodigo() == aux.get(j).getCodigo()) {
                        auxiliar = false;
                    }
                }
                if (auxiliar) {
                    aux.add(rutas.get(i));
                }
            }
            rutas = aux;
        }

    }

    private void mostrarRutasEnTabla() {
        if (rutas.size() > 0) {
            DefaultTableModel model = (DefaultTableModel) tblRuta.getModel();
            int aux = model.getRowCount();
            for (int i = aux; i > 0; i--) {
                model.removeRow(i - 1);
            }
            for (int i = 0; i < rutas.size(); i++) {//Creacion de Celdas
                model.addRow(new Object[]{"", "", "", ""});
                tblRuta.setValueAt(rutas.get(i).getCodigo(), i, 0);
                if (rutas.get(i).isEstado()) {
                    tblRuta.setValueAt("Activado", i, 2);
                } else {
                    tblRuta.setValueAt("Desactivado", i, 2);
                }

                tblRuta.setValueAt(rutas.get(i).getDestino().getNombre(), i, 1);
                int paquetesEnRuta = TransferenciasDB.obtenerPaquetesActivosPorRuta(rutas.get(i).getCodigo()).size();
                tblRuta.setValueAt(paquetesEnRuta, i, 3);
                int paquetesSalidos = TransferenciasDB.obtenerPaquetesNoActivosPorRuta(rutas.get(i).getCodigo()).size();
                tblRuta.setValueAt(paquetesSalidos, i, 4);
                tblRuta.setValueAt(paquetesSalidos + paquetesEnRuta, i, 5);
            }
        } else {
            lblErrorRutas.setVisible(true);
            btnFiltrar.setEnabled(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorRutas;
    private javax.swing.JTable tblRuta;
    private javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables
}
