/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteria.ui.Administracion;

import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import paqueteria.DB.ControladorDB;
import paqueteria.DB.TransferenciasDB;
import paqueteria.GeneradorHTML;
import paqueteria.Ruta.Ruta;

/**
 *
 * @author sergio
 */
public class RutasPopulares extends javax.swing.JInternalFrame {

    private ArrayList<Ruta> rutas;
    private boolean filtrarFechas;

    /**
     * Creates new form RutasPopulares
     */
    public RutasPopulares() {
        filtrarFechas = false;
        rutas = ControladorDB.obtenerRutas();
        initComponents();
        ordenarRutas();
        mostrarRutasEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRuta = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        dateInicio = new com.toedter.calendar.JDateChooser();
        dateFinal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblErrorFechas = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lblErrorRutas = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Rutas Populares");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnExportar.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnExportar.setText("Exportar(Html)");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        tblRuta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#", "Codigo", "Destino", "Paquetes"
            }
        ));
        jScrollPane1.setViewportView(tblRuta);
        if (tblRuta.getColumnModel().getColumnCount() > 0) {
            tblRuta.getColumnModel().getColumn(0).setPreferredWidth(25);
            tblRuta.getColumnModel().getColumn(0).setMaxWidth(25);
        }

        jScrollPane2.setViewportView(jScrollPane1);

        jButton3.setText("Recetear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha Inicio:");

        jLabel4.setText("Fecha Final:");

        lblErrorFechas.setText("Fechas Incorectas");
        lblErrorFechas.setVisible(false);

        jButton4.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButton4.setText("Filtrar(Fecha)");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lblErrorRutas.setText("No Existen Rutas");
        lblErrorRutas.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel3)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lblErrorFechas))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)
                                .addGap(7, 7, 7)
                                .addComponent(jButton3)))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExportar)
                        .addGap(102, 102, 102)
                        .addComponent(lblErrorRutas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(lblErrorFechas)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnExportar)
                    .addComponent(lblErrorRutas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        lblErrorFechas.setVisible(false);
        //Verficacion de las fechas correctas
        if (dateFinal.getDate() == null && dateInicio.getDate() == null) {
            lblErrorFechas.setVisible(true);
        } else if (dateFinal.getDate() == null && dateInicio.getDate().after(Date.from(Instant.now()))) {
            lblErrorFechas.setVisible(true);
        } else if ((dateFinal.getDate() != null && dateInicio.getDate() != null) && dateInicio.getDate().after(dateFinal.getDate())) {
            lblErrorFechas.setVisible(true);
        } else {
            filtrarFechas = true;
            ordenarRutas();
            mostrarRutasEnTabla();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dateInicio.setDate(null);
        dateFinal.setDate(null);
        filtrarFechas = false;
        ordenarRutas();
        mostrarRutasEnTabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        GeneradorHTML.generarReprote(tblRuta, title, LocalDate.now());
        JOptionPane.showMessageDialog(this, "Archivo HTML se encuentra en la carpeta 'Reportes'", "Exportado Correctamente", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnExportarActionPerformed
    //Muestra todas las rutas en la tabal
    private void mostrarRutasEnTabla() {
        if (rutas.size() > 0) {
            DefaultTableModel model = (DefaultTableModel) tblRuta.getModel();
            int aux = model.getRowCount();
            for (int i = aux; i > 0; i--) {
                model.removeRow(i - 1);
            }
            for (int i = 0; i < 3; i++) {//Creacion de Celdas
                model.addRow(new Object[]{"", "", "", ""});
                tblRuta.setValueAt(i + 1, i, 0);
                tblRuta.setValueAt(rutas.get(i).getCodigo(), i, 1);

                tblRuta.setValueAt(rutas.get(i).getDestino().getNombre(), i, 2);
                //En caso de querer filtrar por fechas
                if (filtrarFechas) {
                    LocalDateTime inicioDate;
                    LocalDateTime finalDate;
                    if (dateInicio.getDate() == null) {
                        inicioDate = LocalDateTime.of(2000, 1, 1, 0, 0);
                    } else {
                        inicioDate = LocalDateTime.of(dateInicio.getDate().getYear() + 1900, dateInicio.getDate().getMonth() + 1, dateInicio.getDate().getDate(), 0, 0);
                    }
                    if (dateFinal.getDate() == null) {
                        finalDate = LocalDateTime.now();
                    } else {
                        finalDate = LocalDateTime.of(dateFinal.getDate().getYear() + 1900, dateFinal.getDate().getMonth() + 1, dateFinal.getDate().getDate(), 0, 0);
                    }
                    tblRuta.setValueAt(TransferenciasDB.obtenerPaquetesPorRutaFecha(rutas.get(i).getCodigo(), inicioDate,finalDate).size(), i, 3);
                } else {
                    tblRuta.setValueAt(TransferenciasDB.obtenerPaquetesActivosPorRuta(rutas.get(i).getCodigo()).size()
                            + TransferenciasDB.obtenerPaquetesNoActivosPorRuta(rutas.get(i).getCodigo()).size(), i, 3);
                }

            }
        } else {
            lblErrorRutas.setVisible(true);
        }
    }
//Ordena las rutas por las mas populares
    private void ordenarRutas() {
        rutas = ControladorDB.obtenerRutas();
        ArrayList<Ruta> aux = new ArrayList<>();
        for (int i = 0; i < rutas.size(); i++) {
            aux.add(rutas.get(i));

        }
        int auxiliar;
        Ruta rutaMayor;
        for (int i = 1; i < aux.size(); i++) {
            auxiliar = i;
            rutaMayor = aux.get(i);
            System.out.println("r " + rutaMayor.getCodigo());
            //Si se desea filtrar por fechas
            if (filtrarFechas) {
                LocalDateTime inicioDate;
                LocalDateTime finalDate;
                if (dateInicio.getDate() == null) {
                    inicioDate = LocalDateTime.of(2000, 1, 1, 0, 0);
                } else {
                    inicioDate = LocalDateTime.of(dateInicio.getDate().getYear() + 1900, dateInicio.getDate().getMonth() + 1, dateInicio.getDate().getDate(), 0, 0);
                }
                if (dateFinal.getDate() == null) {
                    finalDate = LocalDateTime.now();
                } else {
                    finalDate = LocalDateTime.of(dateFinal.getDate().getYear() + 1900, dateFinal.getDate().getMonth() + 1, dateFinal.getDate().getDate(), 0, 0);
                }
                while (auxiliar > 0 && TransferenciasDB.obtenerPaquetesPorRutaFecha(rutaMayor.getCodigo(), inicioDate, finalDate).size()
                        > TransferenciasDB.obtenerPaquetesPorRutaFecha(aux.get(auxiliar - 1).getCodigo(), inicioDate, finalDate).size()) {
                    aux.set(auxiliar, aux.get(auxiliar - 1));
                    auxiliar--;
                }
            } else {

                while (auxiliar > 0 && (TransferenciasDB.obtenerPaquetesActivosPorRuta(rutaMayor.getCodigo()).size()
                        + TransferenciasDB.obtenerPaquetesNoActivosPorRuta(rutaMayor.getCodigo()).size())
                        > (TransferenciasDB.obtenerPaquetesActivosPorRuta(aux.get(auxiliar - 1).getCodigo()).size()
                        + TransferenciasDB.obtenerPaquetesNoActivosPorRuta(aux.get(auxiliar - 1).getCodigo()).size())) {
                    aux.set(auxiliar, aux.get(auxiliar - 1));
                    auxiliar--;
                }

            }
            aux.set(auxiliar, rutaMayor);

        }
        rutas = aux;
        for (int i = 0; i < rutas.size(); i++) {
            System.out.println(rutas.get(i).getCodigo());

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnSalir;
    private com.toedter.calendar.JDateChooser dateFinal;
    private com.toedter.calendar.JDateChooser dateInicio;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblErrorFechas;
    private javax.swing.JLabel lblErrorRutas;
    private javax.swing.JTable tblRuta;
    // End of variables declaration//GEN-END:variables
}
