/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteria.ui.Administracion;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import paqueteria.DB.ControladorDB;
import paqueteria.Usuario.Administrador;
import paqueteria.Usuario.Operador;
import paqueteria.Usuario.Usuario;
import paqueteria.ui.IngresoDeUsuario;

/**
 *
 * @author sergio
 */
public class UsuariosExistentes extends javax.swing.JInternalFrame {

    private ArrayList<Usuario> usuarios;
    private int numeroDePuntos = 0;
    private Administrador administrador;
    private boolean advertencia = false;
    private Administracion administracion;

    /**
     * Creates new form UsuariosExistentes
     *
     * @param admin
     * @param administracion
     */
    public UsuariosExistentes(Administrador admin, Administracion administracion) {
        initComponents();
        usuarios = ControladorDB.obtenerUsuarios();
        agregarUsuariosATabla();
        administrador = admin;
        this.administracion = administracion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblCantidadPuntos = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setForeground(new java.awt.Color(1, 1, 1));
        setTitle("Usuarios Existentes");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Jerarquia"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jButton1.setText("Eliminar");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("User Name:");
        jLabel1.setOpaque(true);

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(254, 254, 254));
        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setText("Puntos De Control A Cargo:");
        jLabel2.setOpaque(true);

        lblCantidadPuntos.setBackground(new java.awt.Color(254, 254, 254));
        lblCantidadPuntos.setOpaque(true);

        lblUserName.setBackground(new java.awt.Color(254, 254, 254));
        lblUserName.setOpaque(true);

        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel3.setText("Ingrese User Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidadPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblCantidadPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButton1))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        int row = tblUsuarios.getSelectedRow();
        if (row >= 0) {
            lblUserName.setText(usuarios.get(row).getUserName());
            if (usuarios.get(row).getJerarquia() == 2) {
                numeroDePuntos = ControladorDB.obtenerPuntosDeControlPorOperador(usuarios.get(row)).size();
                lblCantidadPuntos.setText(String.valueOf(numeroDePuntos));
            } else {
                numeroDePuntos = 0;
                lblCantidadPuntos.setText("---");
            }
            jButton1.setEnabled(true);
        } else {
            lblCantidadPuntos.setText("");
            lblUserName.setText("");
        }
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (numeroDePuntos == 0) {
            Usuario usuarioAElimnar = usuarios.get(tblUsuarios.getSelectedRow());
            if (administrador.getUserName().equals(usuarioAElimnar.getUserName())) {
                if (advertencia) {
                    ControladorDB.eliminarUsuario(usuarioAElimnar);
                    usuarios.remove(tblUsuarios.getSelectedRow());
                    agregarUsuariosATabla();
                     JOptionPane.showMessageDialog(this,"UserName :"+usuarioAElimnar.getUserName(), "Usuario Eliminado Correctamente", JOptionPane.INFORMATION_MESSAGE);
                    logOut();
                } else {
                    JOptionPane.showMessageDialog(this, "Si Deseas Elimnar Tu Cuenta Y Causar Un LogOut Preciona Eliminar De Nuevo", "Este Usuario Es Tuyo", JOptionPane.INFORMATION_MESSAGE);
                    advertencia = true;
                }
            } else {
                ControladorDB.eliminarUsuario(usuarioAElimnar);
                usuarios.remove(tblUsuarios.getSelectedRow());
                JOptionPane.showMessageDialog(this,"UserName :"+usuarioAElimnar.getUserName(), "Usuario Eliminado Correctamente", JOptionPane.INFORMATION_MESSAGE);
                agregarUsuariosATabla();
                
            }
        } else {
            JOptionPane.showMessageDialog(this, "Este Usuario Esta A Cargo De " + numeroDePuntos + " Puntos De Control", "Error Al Eliminar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBuscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyPressed
        
    }//GEN-LAST:event_txtBuscadorKeyPressed

    private void txtBuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyTyped
        
    }//GEN-LAST:event_txtBuscadorKeyTyped

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        buscar(txtBuscador.getText());
        agregarUsuariosATabla();
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void txtBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyReleased
        buscar(txtBuscador.getText());
        agregarUsuariosATabla();
    }//GEN-LAST:event_txtBuscadorKeyReleased
    private void buscar(String palabra){
        System.out.println(palabra);
        ArrayList<Usuario> aux = new ArrayList<>();
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getUserName().startsWith(palabra)) {
                aux.add(usuarios.get(i));
            }            
        }
        boolean auxiliar=true;
        for (int i = 0; i < usuarios.size(); i++) {
            for (int j = 0; j < aux.size(); j++) {
                 if (usuarios.get(i)==aux.get(j)) {
                    auxiliar=false;
                }
                
            }   
            if (auxiliar) {
                    aux.add(usuarios.get(i));
                }
        }
        usuarios= aux;
    }
    private void logOut() {
        this.setVisible(false);
        administracion.setVisible(false);
        IngresoDeUsuario inicio = new IngresoDeUsuario();
        inicio.setVisible(true);
    }

    private void agregarUsuariosATabla() {
        lblCantidadPuntos.setText("");
        lblUserName.setText("");
        DefaultTableModel model = (DefaultTableModel) tblUsuarios.getModel();
        int aux = model.getRowCount();
        for (int i = aux; i > 0; i--) {
            model.removeRow(i - 1);
        }
        for (int i = 0; i < usuarios.size(); i++) {//Creacion de Celdas
            model.addRow(new Object[]{"", ""});
            tblUsuarios.setValueAt(usuarios.get(i).getUserName(), i, 0);

            switch (usuarios.get(i).getJerarquia()) {
                case 1:
                    tblUsuarios.setValueAt("Administrador", i, 1);
                    break;
                case 2:
                    tblUsuarios.setValueAt("Operador", i, 1);
                    break;
                case 3:
                    tblUsuarios.setValueAt("Recepcionista", i, 1);
                    break;
                default:
                    throw new AssertionError();
            }

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCantidadPuntos;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables
}
